apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: project-image-prod-yml
  namespace: YOUR_PROJECT_ID
  labels:
    cloudcontainers-googleapis-com-container-name: project-image-prod
spec:
  template:
    spec:
      serviceAccountName: YOUR_SERVICE_ACCOUNT
      containers:
        - image: IMAGE_NAME
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
